---
title: "Reproducing Karin et al's longitudal model of senescent cell growth"
output:
  pdf_document: default
  html_document:
    df_print: paged
params:
  data_dir: ../dat/
  refit_models: T
---

```{r include=FALSE}
library(brms)
library(dplyr)
library(foreach)
library(ggplot2)
library(ggpubr)
library(latex2exp)
library(loo)
library(purrr)
library(reshape2)
library(stringr)
library(tidyverse)

# Stan-specific stuff
library(bridgesampling)
library(rstan)
library(gridExtra)
rstan_options (auto_write = TRUE)
options(mc.cores = parallel::detectCores())
set.seed(3) # for reproductibility
```

# Loading and visualizing the data
```{r}
snc_counts_fname <- str_c(
  params$data_dir, "raw", "senescent_cells_and_the_dynamics_of_aging__fig_2.csv",
  sep="/"
)
raw_snc_counts <- read.csv(snc_counts_fname, header=TRUE) %>%
  drop_na()
snc_counts <- melt(
  data = raw_snc_counts, 
  id.vars = "mouse.week", 
  measure.vars = c(
    "X8", "X16", "X24", "X32", "X40", "X48", "X56", "X64", "X72", "X80"
  ),
  value.name = "TBL_x_10_5"
)
snc_counts <- snc_counts %>%
  rename(week = "variable", mouse = "mouse.week")
snc_counts$week <- map_int(snc_counts$week, function (week) { return(as.integer(substr(week, 2, str_length(week)))) })
length(unique(snc_counts$week))
```

```{r}
ggplot(
  data = snc_counts, 
  aes(x = week, y = TBL_x_10_5, color = mouse, group = mouse)
) +
  xlab("Week") + ylab(TeX("$ TBL \\times 10^5 $")) +
  scale_color_gradientn(colours = rainbow(5)) + geom_line() + geom_point()
max(snc_counts$mouse)
```


```{r}
norm_const <- mean(
  snc_counts[snc_counts$week %in% c(8, 16, 24),]$TBL_x_10_5, na.rm = T
)
snc_counts$norm_abundance <- snc_counts$TBL_x_10_5 / norm_const
mean_abundances <- aggregate(
  snc_counts$norm_abundance, list(snc_counts$week), mean, na.rm = T
)$x
stddev_abundances <- aggregate(
  snc_counts$norm_abundance, list(snc_counts$week), sd, na.rm = T
)$x
mean_stddev_abundances <- data.frame(
  mean = mean_abundances,
  stddev = stddev_abundances,
  week = unique(snc_counts$week)
)
p <- ggplot(mean_stddev_abundances, aes(x=week, y=mean)) + geom_point() +
    geom_errorbar(aes(ymin=mean-stddev/2, ymax=mean+stddev/2), width=.2,
                 position=position_dodge(0.05))
print(p)
```

# Fitting our three models on longitudinal data
## Data processing
```{r}
# Time series of SnC counts
mice <- unique(snc_counts$mouse)
weeks <- unique(snc_counts$week)
n_mice <- length(mice)
n_weeks <- length(weeks)
snc_abundance <- matrix(nrow = n_mice, ncol=n_weeks)
for (m in 1:n_mice) {
  for (t in 1:n_weeks) {
    mouse <- mice[m]
    week <- weeks[t]
    mouse_week_index <- which(snc_counts$mouse == mouse & snc_counts$week == week)[1]
    snc_abundance[m, t] <- snc_counts$norm_abundance[mouse_week_index]
  }
}

# times
t <- sort(weeks) # 8 hard-coded to match data
t0 = 0

# initial conditions
y0 = c(1)
dim(y0) <- (1)

# data for Stan
data_snc <- list(n_weeks = n_weeks, n_mice = n_mice, y0 = y0, t0 = t0, ts = t, cells = snc_abundance)

saveRDS(snc_counts, "saved_fit/snc_counts.RDS")
saveRDS(data_snc, "saved_fit/data_snc.RDS")

# number of MCMC steps
niter <- 2000
```

## MCMC sampling
### SR model

```{r}
if (params$refit_models) {
  model <- stan_model("snc_sr_model.stan")
  fit_snc_sr_model <- sampling(
    model,
    data = data_snc,
    iter = niter,
    chains = 4
  )
  saveRDS(fit_snc_sr_model, "saved_fit/fit_snc_sr_model.RDS")
} else {
  fit_snc_sr_model <- readRDS("saved_fit/fit_snc_sr_model.RDS")
}
```

### USR model

```{r}
if (params$refit_models) {
  model <- stan_model("snc_usr_model.stan")
  fit_snc_usr_model <- sampling(
    model,
    data = data_snc,
    iter = niter,
    chains = 4
  )
  saveRDS(fit_snc_usr_model, "saved_fit/fit_snc_usr_model.RDS")
} else {
  fit_snc_usr_model <- readRDS("saved_fit/fit_snc_usr_model.RDS")
}
```

### SIS model
```{r}
if (params$refit_models) {
  model <- stan_model("snc_sis_model.stan")
  fit_snc_sis_model <- sampling(
    model,
    data = data_snc,
    iter = niter,
    chains = 4,
  )
  saveRDS(fit_snc_sis_model, "saved_fit/snc_sis_model.RDS")
} else {
  fit_snc_sis_model <- readRDS("saved_fit/snc_sis_model.RDS")
}
```

## Fit diagnostics
```{r}
sr_pars=c('eta', 'beta', 'sigma', 'lp__', 'log_likelihood')
print(fit_snc_sr_model, pars = sr_pars, digits_summary = 4)
```

```{r}
usr_pars=c('eta', 'beta', 'sigma', 'log_likelihood', 'lp__')
print(fit_snc_usr_model, pars = usr_pars, digits_summary = 4)
```

```{r}
sis_pars=c('eta', 'beta', 'sigma', 'alpha', 'll', 'log_likelihood', 'lp__')
print(fit_snc_sis_model, pars = sis_pars, digits_summary = 4)
```


```{r}
pairs(fit_snc_sr_model, pars=sr_pars)
```

```{r}
pairs(fit_snc_usr_model, pars = usr_pars)
```

```{r}
pairs(fit_snc_sis_model, pars = sis_pars)
```


```{r}
stan_dens(fit_snc_sr_model, pars = sr_pars, separate_chains = TRUE)
```

```{r}
stan_dens(fit_snc_usr_model, pars = usr_pars, separate_chains = TRUE)
```

```{r}
stan_dens(fit_snc_sis_model, pars = sis_pars, separate_chains = TRUE)
```

## Trajectory plots
```{r}
snc_sr_counts_pred <- cbind(
  as.data.frame(
    summary(
      fit_snc_sr_model, pars = "pred_cells_means", 
      probs = c(0.05, 0.5, 0.95)
    )$summary
  ), 
  t, 
  mean_abundances,
  stddev_abundances
)
snc_usr_counts_pred <- cbind(
  as.data.frame(
    summary(
      fit_snc_usr_model, pars = "pred_cells_means", 
      probs = c(0.05, 0.5, 0.95)
    )$summary
  ), 
  t, 
  mean_abundances,
  stddev_abundances
)
snc_sis_counts_pred <- cbind(
  as.data.frame(
    summary(
      fit_snc_sis_model, pars = "pred_cells_means", 
      probs = c(0.05, 0.5, 0.95)
    )$summary
  ), 
  t, 
  mean_abundances,
  stddev_abundances
)
snc_sis_ll_counts_pred <- cbind(
  as.data.frame(
    summary(
      fit_snc_sis_model, pars = "pred_ll_cells_means", 
      probs = c(0.05, 0.5, 0.95)
    )$summary
  ), 
  t, 
  mean_abundances,
  stddev_abundances
)
colnames(snc_sr_counts_pred) <- make.names(colnames(snc_usr_counts_pred)) # to remove % in the col names
colnames(snc_usr_counts_pred) <- make.names(colnames(snc_usr_counts_pred)) # to remove % in the col names
colnames(snc_sis_counts_pred) <- make.names(colnames(snc_sis_counts_pred)) # to remove % in the col names
colnames(snc_sis_ll_counts_pred) <- make.names(colnames(snc_sis_ll_counts_pred)) # to remove % in the col names


p_usr <- ggplot(snc_usr_counts_pred, mapping = aes(x = t)) +
  geom_ribbon(data = snc_usr_counts_pred, aes(ymin = X5., ymax = X95.), fill = "blue", alpha = 0.6) +
  geom_line(mapping = aes(x = t, y = X50.)) + 
  geom_point(mapping = aes(y = mean_abundances)) +
  geom_errorbar(
    data = snc_sr_counts_pred, 
    aes(
      ymin=mean_abundances - stddev_abundances/2,
      ymax=mean_abundances + stddev_abundances/2,
    ),
    width=.2,
    position=position_dodge(0.05),
  ) +
  labs(title = "Unsaturated Removal Model Predictions", x = "Week", y = "SnC (normalized)", color = "name")

p_sr <- ggplot(snc_sr_counts_pred, mapping = aes(x = t)) +
  geom_ribbon(aes( ymin = X5., ymax = X95.), fill = "orange", alpha = 0.6) +
  geom_line(mapping = aes(x = t, y = X50.)) + 
  geom_point(mapping = aes(y = mean_abundances)) +
  geom_errorbar(
    aes(
      ymin=mean_abundances - stddev_abundances/2,
      ymax=mean_abundances + stddev_abundances/2
    ),
    width=.2,
    position=position_dodge(0.05)
  ) +
  scale_x_continuous(name = "Week", breaks=t, labels=t, limits = c(8, 80)) +
  labs(title = "Saturated Removal Model Predictions", x = "Week", y = "SnC (normalized)", color = "name")
p_sis <- ggplot(snc_sis_counts_pred, mapping = aes(x = t)) +
  geom_ribbon(aes( ymin = X5., ymax = X95.), fill = "orange", alpha = 0.6) +
  geom_line(mapping = aes(x = t, y = X50.)) + 
  geom_line(data = snc_sis_ll_counts_pred, aes(x = t, y = X50.), col = "grey") +
  geom_point(mapping = aes(y = mean_abundances)) +
  geom_errorbar(
    aes(
      ymin=mean_abundances - stddev_abundances/2,
      ymax=mean_abundances + stddev_abundances/2
    ),
    width=.2,
    position=position_dodge(0.05)
  ) +
  scale_x_continuous(name = "Week", breaks=t, labels=t, limits = c(8, 80)) +
  labs(title = "SIS Model Predictions", x = "Week", y = "SnC (normalized)", color = "name")
ggarrange(p_usr, p_sr, p_sis)
```


# Model comparison
```{r}
fit_snc_sr_model.bridge <- bridge_sampler(fit_snc_sr_model, silent = T)
fit_snc_sis_model.bridge <- bridge_sampler(fit_snc_sis_model, silent = T)
fit_snc_usr_model.bridge <- bridge_sampler(fit_snc_usr_model, silent = T)
bayes_factor(fit_snc_sis_model.bridge, fit_snc_sr_model.bridge)
bayes_factor(fit_snc_sis_model.bridge, fit_snc_usr_model.bridge)
bayes_factor(fit_snc_sr_model.bridge, fit_snc_usr_model.bridge)
post_prob(fit_snc_sis_model.bridge, fit_snc_sr_model.bridge, fit_snc_usr_model.bridge)
```


