---
title: "priors"
author: "Stephen Malina"
date: "12/8/2020"
output: html_document
---

```{r setup, include=FALSE}
library(brms)
library(dplyr)
library(foreach)
library(ggplot2)
library(ggpubr)
library(latex2exp)
library(loo)
library(purrr)
library(reshape2)
library(stringr)
library(tidyverse)

# Stan-specific stuff
library(bridgesampling)
library(rstan)
library(gridExtra)
rstan_options (auto_write = TRUE)
options (mc.cores = parallel::detectCores ())
set.seed(3) # for reproductibility
```

# Colors
```{r}
c_light <- c("#DCBCBC")
c_light_highlight <- c("#C79999")
c_mid <- c("#B97C7C")
c_mid_highlight <- c("#A25050")
c_dark <- c("#8F2727")
c_dark_highlight <- c("#7C0000")

c_dark_trans <- c("#8F272780")
c_green_trans <- c("#00FF0080")
```

# Half-normal prior
```{r, echo=FALSE}
stan(file='half_normal_prior_tune.stan', iter=1, warmup=0, chains=1,
     seed=4838282, algorithm="Fixed_param")
```

```{r}
lambda <- seq(0, 1, 0.001)

plot(lambda, dnorm(lambda, 0, .3), type="l", col=c_dark_highlight, lwd=2,
     xlab="lambda", ylab="Prior Density", yaxt='n')

lambda99 <- seq(0, 1, 0.001)
dens <- dnorm(lambda99, 0, .3)
lambda99 <- c(lambda99, 1, 0)
dens <- c(dens, 0, 0)

polygon(lambda99, dens, col=c_dark, border=NA)
```


